import assert from "node:assert/strict";
import test from "node:test";
import {
  analyzeDiffText,
  extractFunctions,
  extractImports,
  looksGenerated,
} from "./collect/git.js";

test("timeout and skip heuristics fire on added lines", () => {
  const diff = `
diff --git a/t.test.ts b/t.test.ts
--- a/t.test.ts
+++ b/t.test.ts
@@
-  timeout: 1000
+  timeout: 5000
+  it.skip("flaky checkout", () => {});
`;
  const h = analyzeDiffText(diff);
  assert.ok(h.timeout_bumps.length >= 1);
  assert.ok(h.skip_added.length >= 1);
});

test("jest-style trailing timeout argument is detected", () => {
  const diff = `
-}, 1000);
+}, 5000);
`;
  const h = analyzeDiffText(diff);
  assert.ok(h.timeout_bumps.length >= 1);
});

test("sql concat heuristic", () => {
  const diff = `
+    return db.execute("SELECT * FROM users WHERE name LIKE '%" + q + "%'");
`;
  const h = analyzeDiffText(diff);
  assert.ok(h.sql_concat.length >= 1);
});

test("extracts imports into recognizable module specifiers", () => {
  const src = `
import express from "express";
import { Pool } from "pg";
import Stripe from "stripe";
const React = require("react");
`;
  const specs = extractImports(src);
  assert.ok(specs.includes("express"));
  assert.ok(specs.includes("pg"));
  assert.ok(specs.includes("stripe"));
  assert.ok(specs.includes("react"));
});

test("function sizes are approximate", () => {
  const src = `
function a() {
  return 1;
}

function b() {
  const x = 1;
  const y = 2;
  return x + y;
}
`;
  const fns = extractFunctions(src);
  assert.equal(fns[0]?.name, "b");
  assert.ok((fns[0]?.approx_lines ?? 0) >= (fns[1]?.approx_lines ?? 0));
});

test("generated header is detected", () => {
  assert.equal(looksGenerated("// Code generated by protoc. DO NOT EDIT.\n", "x.ts"), true);
  assert.equal(looksGenerated("export const x = 1;\n", "x.ts"), false);
});
