import assert from "node:assert/strict";
import test from "node:test";
import { analyzeSource, compareSources } from "./collect/ast.js";
import { looksGenerated } from "./collect/git.js";

test("timeout bump and skip are detected from AST, not added-line regex", () => {
  const hits = compareSources(
    "t.test.ts",
    `test("checkout", () => {}, 1000);\n`,
    `test("checkout", () => {}, 5000);\nit.skip("flaky checkout", () => {});\n`,
  );
  assert.ok(hits.timeout_bumps.length >= 1, String(hits.timeout_bumps));
  assert.ok(hits.skip_added.length >= 1, String(hits.skip_added));
});

test("SQL concatenation is an AST binary/template hit", () => {
  const hits = compareSources(
    "db.ts",
    `db.execute("SELECT 1");\n`,
    `db.execute("SELECT * FROM users WHERE name LIKE '%" + q + "%'");\n`,
  );
  assert.ok(hits.sql_concat.length >= 1, String(hits.sql_concat));
});

test("empty catch is an empty catch_clause, not a one-line regex", () => {
  const hits = compareSources(
    "x.ts",
    `try { run() } catch (e) { throw e }\n`,
    `try { run() } catch (e) {}\n`,
  );
  assert.ok(hits.empty_catch.length >= 1, String(hits.empty_catch));
});

test("TypeScript imports and function sizes come from the tree", () => {
  const src = `
import express from "express";
import { Pool } from "pg";
import Stripe from "stripe";
const React = require("react");

function a() {
  return 1;
}

function b() {
  const x = 1;
  const y = 2;
  return x + y;
}
`;
  const ast = analyzeSource("app.ts", src);
  assert.ok(ast.imports.includes("express"), String(ast.imports));
  assert.ok(ast.imports.includes("pg"), String(ast.imports));
  assert.ok(ast.imports.includes("stripe"), String(ast.imports));
  assert.ok(ast.imports.includes("react"), String(ast.imports));
  assert.equal(ast.functions[0]?.name, "b");
  assert.ok((ast.functions[0]?.approx_lines ?? 0) >= (ast.functions[1]?.approx_lines ?? 0));
});

test("generated header is detected", () => {
  assert.equal(looksGenerated("// Code generated by protoc. DO NOT EDIT.\n", "x.ts"), true);
  assert.equal(looksGenerated("export const x = 1;\n", "x.ts"), false);
});

test("Python empty except and sleep are parsed as Python", () => {
  const hits = compareSources(
    "t.py",
    `def f():\n    return 1\n`,
    `def f():\n    try:\n        g()\n    except Exception:\n        pass\n    time.sleep(1)\n`,
  );
  assert.ok(hits.languages.includes("python"), String(hits.languages));
  assert.ok(hits.empty_catch.length >= 1, String(hits.empty_catch));
  assert.ok(hits.sleep_added.length >= 1, String(hits.sleep_added));
});

test("Go swallowed error and SQL concat are parsed as Go", () => {
  const hits = compareSources(
    "main.go",
    `package main\nfunc F() { x() }\n`,
    `package main\nfunc F() {\n  if err != nil {\n  }\n  db.Query("SELECT * FROM t WHERE n=" + q)\n}\n`,
  );
  assert.ok(hits.languages.includes("go"), String(hits.languages));
  assert.ok(hits.empty_catch.length >= 1, String(hits.empty_catch));
  assert.ok(hits.sql_concat.length >= 1, String(hits.sql_concat));
});

test("Java empty catch is parsed as Java", () => {
  const hits = compareSources(
    "A.java",
    `class A { void f() { try { x(); } catch (Exception e) { throw e; } } }\n`,
    `class A { void f() { try { x(); } catch (Exception e) {} } }\n`,
  );
  assert.ok(hits.languages.includes("java"), String(hits.languages));
  assert.ok(hits.empty_catch.length >= 1, String(hits.empty_catch));
});
